---
title: An R Markdown document converted from "Copy_of_ListsIn_R.ipynb"
output: html_document
---


# Lists in R

## 1. Creating

```{r}
namesR=list("Qing", "Françoise", "Raúl", "Bjork","Marie","Jim","Tere","Tina")
agesR=list(32,33,28,30,29,33,34,27)
countryR=list("China", "Senegal", "España", "Norway","Korea","USA","Bolivia","Portugal")
educationR=list("Bach", "Bach", "Master", "PhD","PhD", "Master","Master","PhD")
```

```{r}
typeof(namesR)
```

```{r}
namesR
```

## 2. Accessing

```{r}
# the value in the first location
agesR[[1]]
```

```{r}
typeof(agesR[[1]]) # # the value in the first location is ?
```

```{r}
# the first location
agesR[1]
```

```{r}
typeof(agesR[1]) ## the first location is?
```

### Slices

```{r}
# consecutive
# agesR[[2:4]] # will not work
agesR[2:4]
```

```{r}
# non consecutive with step or pattern
agesR[seq(2,8,2)]
```

** Where is the 30 coming from? Row 4 but where is it referenced? Something to do with 'seq' maybe? **

```{r}
# non consecutive without step or pattern
agesR[c(1,3,4)]
```

## Replacing

### by Position

```{r}

countryR[[3]]="Spain"

# list changed:
countryR
```

Several positions?

```{r}
# check
##countryR=list("China", "Senegal", "España", "Norway","Korea","USA","Bolivia","Portugal")
countryR[c(3,6)]=list("Spain Kingdom","US_America")
countryR
```

### By Value

```{r}
countryR[countryR=='China']="PR China"
countryR
```

## Deleting

### By Position

```{r}
countryR[1]=NULL
countryR
```

```{r}
# several positions

listR=list(1,2,3,4,5,6)
listR[2:4]=NULL

#now:
listR
```

```{r}
# non consecutive

listR=list(11,22,33,44,55,66)
listR[c(2,4,6)]=NULL
listR
```

### by Value

```{r}

# by value
listR=list(1,'a',45,'b','a')
listR=listR[!listR %in% list('a')]
listR
```

## Inserting values

```{r}
# at the end
listR=list(1,'a',45,'b','a')
listR=append(listR,'cde')
listR
```

```{r}
# specific position

listR=list(1,'a',45,'b','a')
listR=append(listR,'cde',after=2)
listR
```

## Concatenating

```{r}
listA_R=list(1,2,3)
listB_R=list('a', 'b', 'c')
append(listA_R, listB_R)
```

```{r}
#notice

append(listA_R, list(listB_R))
```

