---
title: An R Markdown document converted from "Copy_of_Applying_Fun_R.ipynb"
output: html_document
---

# Applying functions in R

Installing to read Excel files:

```{r}
install.packages('rio') ## code requests installing the package 'rio'
```

# reading data

```{r}
linkGit="https://github.com/DACSS-Fundamentals/overview/raw/refs/heads/main/FSI-2023-DOWNLOAD.xlsx" ## code to request a file from a specific link

fragility23=rio::import(file = linkGit) ## code to use the package rio, import the file above and name it 'fragility23'
```

```{r}
str(fragility23) ## code requests the data structure of 'fragility23' to see the types of data in each column
```

## Apply square root function?

```{r}
sqrt(fragility23) ## code can't apply the square root function to the entire data frame in R
```

```{r}
sqrt(fragility23[,4:5]) ## code requests the square root of all the values in columns 4 and 5 to show individual output values
```

```{r}
sqrt(fragility23$Total) ## code requests the square root of each value in the total column 
```

```{r}
sqrt(fragility23$Total[1]) ## code requests the square root of the first value in the total column
```

## Applying **sum()**:

```{r}
sum(fragility23[,4:5]) ## code requests the sum of all values in column 4 and 5
```

```{r}
print(apply(fragility23[,4:5],2,sum)) ## code requests the sum of all values in each column 4 and 5 to show as separate totals
```

```{r}
typeof(apply(fragility23[,4:5],2,sum)) ## code requests the data type of the sums of the values in columns 4 and 5. Since it says 'double' and not list, it is a vector
```

If you do not see **list**, then it is a vector. ⏫

```{r}
# sum by row
print(apply(fragility23[,4:5],1,sum))
```

### Apply by iterating:

```{r}
print(lapply(fragility23[,4:5],sum))
```

Notice output of **lapply**:

```{r}
typeof(lapply(fragility23[,4:5],sum))
```

```{r}
class(lapply(fragility23[,4:5],sum))
```

Notice output of **sapply**:

```{r}
print(sapply(fragility23[,4:5],sum))
```

```{r}
class(sapply(fragility23[,4:5],sum))
```

Similarly:

```{r}
print(lapply(fragility23[,4:5],sqrt))
```

```{r}
class(lapply(fragility23[,4:5],sqrt))
```

```{r}
print(sapply(fragility23[,4:5],sqrt))
```

```{r}
class(sapply(fragility23[,4:5],sqrt))
```

Now our own function:

```{r}
theOnesOK = function(DF_country_and_variable) {
  variable_values <- DF_country_and_variable[,2]
  avg_value <- mean(variable_values, na.rm = TRUE)
  is_above <- ifelse(variable_values > avg_value, "Above Average", "Below/At Average")
  DF_country_and_variable$Status <- is_above
  return(DF_country_and_variable)
}
```

```{r}
theOnesOK(fragility23[,c('Country','S1: Demographic Pressures')])
```

```{r}
mystery=function(DF,positionsToUse,CountryColumn='Country'){
  newDF=DF[,c(CountryColumn),drop = FALSE]
  average='average'
  newDF[,average]=apply(DF[,positionsToUse],1,mean,na.rm = TRUE)
  return(newDF[,c(CountryColumn,average)])
}
```

```{r}
mystery(fragility23,4:6)
```

